name: Update latest user agents
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  
jobs:
  build:
    name: Update latest user agents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python --version
      - run: pip install -r requirements.txt
      - run: python update.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
